version: "3.8"
services:
  mariadb:
    image: bitnami/mariadb:11.1.6-debian-12-r0
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOTPASS}
      MARIADB_DATABASE: ${GHOST_DB_DATABASE}
      MARIADB_USER: ${GHOST_DB_USER}
      MARIADB_PASSWORD: ${GHOST_DB_PASSWORD}
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - ghost_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mariadb_data:
networks:
  ghost_network:
    external: true
    name: ghost_network