version: "3.8"
services:
  ghost:
    image: ghost:5.116.1-alpine
    container_name: ghost
    restart: unless-stopped
    environment:
      NODE_ENV: production
      url: https://www.faebol.com
      database__client: ${GHOST_DB_CLIENT}
      database__connection__host: ${GHOST_DB_HOST}
      database__connection__user: ${GHOST_DB_USER}
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ${GHOST_DB_DATABASE}
      database__connection__port: ${GHOST_DB_PORT}
      mail__transport: ${MAIL_TRANSPORT}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASS}
      mail__from: ${NOREPLY}
      server__host: 0.0.0.0
    expose:
      - "2368"
    volumes:
      - ghost_data:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
    networks:
      - traefik_proxy
      - ghost_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.ghost.rule=Host(`www.faebol.com`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=le"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
#      - "traefik.http.routers.ghost.middlewares=secure-headers@file"
      - "traefik.http.middlewares.ghost-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.ghost.middlewares=ghost-headers"
volumes:
  ghost_data:

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
  ghost_network:
    external: true
    name: ghost_network